### YamlMime:ModuleUnit
uid: learn.wwl-playground.work-with-computers.work-with-applications
title: Work with Applications
metadata:
  title: Work with Applications - Learn
  description: Work with Applications - Learn
  ms.date: 01/31/2019
  author: bcafferky
  ms.author: brcaffer
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/3-work-with-applications.md)]