### YamlMime:ModuleUnit
uid: learn.wwl-playground.work-with-applications.what-is-an-application
title: What is an Application
metadata:
  title: What is an Application - Learn
  description: What is an Application - Learn
  ms.date: 01/31/2019
  author: bcafferky
  ms.author: brcaffer
  ms.topic: interactive-tutorial
  ms.prod: learning-windows
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/2-what-is-an-application.md)]